#################################### 项目启动端口 ######################################
server:
  port: 8001

#################################### 数据库 #########################################
spring:
  datasource:
    url: jdbc:mysql://106.12.38.52:3306/chat_room?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

#################################### mybatis-plus 配置##################################
mybatis-plus:
  mapper-locations: classpath*:mapper/mysql/**/*.xml
  typeAliasesPackage: com.zxl.**.vo